GRANT SELECT ON ALL TABLES IN SCHEMA public TO reader;
GRANT SELECT ON ALL TABLES IN SCHEMA cellline TO reader;
GRANT SELECT ON ALL TABLES IN SCHEMA tissue TO reader;

GRANT USAGE ON SCHEMA public TO reader;
GRANT USAGE ON SCHEMA cellline TO reader;
GRANT USAGE ON SCHEMA tissue TO reader;
