apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: datavisyn-ecr-token-refresher
spec:
  # run every 8 hours
  schedule: "0 */8 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: datavisyn-ecr-token-refresher
            image: 922145058410.dkr.ecr.eu-central-1.amazonaws.com/phovea/kubectl:latest
            imagePullPolicy: IfNotPresent
            env:
              - name: AWS_ACCESS_KEY_ID
                valueFrom:
                  secretKeyRef:
                    name: datavisyn-ecr-token
                    key: AWS_ACCESS_KEY_ID
              - name: AWS_SECRET_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    name: datavisyn-ecr-token
                    key: AWS_SECRET_ACCESS_KEY
              - name: https_proxy
                valueFrom:
                  secretKeyRef:
                    name: internet-proxy-access
                    key: HTTPS_PROXY
              - name: http_proxy
                valueFrom:
                  secretKeyRef:
                    name: internet-proxy-access
                    key: HTTP_PROXY
            volumeMounts:
              - name: ordino-ecr-token-refresher-configuration
                mountPath: /data
            command:
              - /bin/sh
              - /data/refresh-ecr-token.sh
              - "188237246440"
              - eu-central-1
              - datavisyn-ecr-registry
          volumes:
            - name: ordino-ecr-token-refresher-configuration
              configMap:
                name: ordino-ecr-token-refresher-configuration
          restartPolicy: OnFailure
          imagePullSecrets:
            - name: ordino-eu-central-1-ecr-registry
