apiVersion: batch/v1
kind: Job
metadata:
  name: ordino-ecr-token-refresher-now
spec:
  template:
    spec:
      containers:
      - name: ordino-ecr-token-refresher
        image: 922145058410.dkr.ecr.eu-central-1.amazonaws.com/phovea/kubectl:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: ordino-ecr-token
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: ordino-ecr-token
                key: AWS_SECRET_ACCESS_KEY
          - name: https_proxy
            valueFrom:
              secretKeyRef:
                name: internet-proxy-access
                key: HTTPS_PROXY
          - name: http_proxy
            valueFrom:
              secretKeyRef:
                name: internet-proxy-access
                key: HTTP_PROXY
        volumeMounts:
          - name: ordino-ecr-token-refresher-configuration
            mountPath: /data
        command:
          - /bin/sh
          - /data/refresh-ecr-token.sh
      volumes:
        - name: ordino-ecr-token-refresher-configuration
          configMap:
            name: ordino-ecr-token-refresher-configuration
      restartPolicy: OnFailure
      imagePullSecrets:
        - name: ordino-eu-central-1-ecr-registry
