apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: ordino-job-cleanup
spec:
  schedule: "30 2 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: ordino-job-cleanup
            image: 922145058410.dkr.ecr.eu-central-1.amazonaws.com/phovea/kubectl:latest
            imagePullPolicy: IfNotPresent
            volumeMounts:
              - name: ordino-ecr-token-refresher-configuration
                mountPath: /data
            command:
              - /bin/sh
              - -c 
              - 'kubectl --kubeconfig /data/admin.conf delete $(kubectl --kubeconfig /data/admin.conf get jobs -o name | grep "job/datavisyn-ecr-token-*\|job/ordino-ecr-token*\|job/ordino-dev-nightly*\|job/ordino-biberach-dev-nightly*\|job-ordino-job-cleanup*")'
          volumes:
            - name: ordino-ecr-token-refresher-configuration
              configMap:
                name: ordino-ecr-token-refresher-configuration
          restartPolicy: OnFailure
          imagePullSecrets:
            - name: ordino-eu-central-1-ecr-registry
