version: '2.0'
services:
  _host:
    depends_on:
    - db_publicdb
    links:
    - db_publicdb:publicdb
  db_publicdb:
    image: postgres:10-alpine
    environment:
       POSTGRES_USER: publicdb
       POSTGRES_PASSWORD: publicdb
       POSTGRES_DB: publicdb
    volumes:
    - db_publicdb_data:/var/lib/postgresql/data
volumes:
  db_publicdb_data:
